modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="createvoicelink"
version="1.0.0"
displayName="Create: Voice Link"
description="Voice-activated Create Redstone Links"

[[dependencies.createvoicelink]]
modId="neoforge"
type="required"
versionRange="[21.1,)"

[[dependencies.createvoicelink]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"

[[dependencies.createvoicelink]]
modId="create"
type="required"
versionRange="[6.0,)"

[[dependencies.createvoicelink]]
modId="voicechat"
type="required"
versionRange="[2.5,)"
